### ISSUE TITLE
missing task point

### ISSUE THREAD

**Issue by rezasaddat** [denapey/tes#1]
![image](https://user-images.githubusercontent.com/31197736/104031897-ed9e0a80-51ff-11eb-9e23-eeb3f45dd99f.png)

why navigate menu not implemented? 
to upload and the page content different with mockup? we must navigate to user info at the right top to access upload menu?

![image](https://user-images.githubusercontent.com/31197736/104031868-e5de6600-51ff-11eb-84cf-8959139d7225.png)

missing bar chart not using json file like line chart

range date function implemented on line chart only, not bar chart

overall ok

**Comment by denapey** [comment]
Ok, done.
Sorry, I need additional time to do it


![update](https://user-images.githubusercontent.com/2362252/104085977-36000b80-5286-11eb-9002-af68fbe02083.png)
